import {
  prepare,
  finalize,
  downloadIcons,
  scaleIcons,
  convertStrokeIconsToFill,
  writeIcons
} from './utils';

const COMMENT = "/** DO NOT EDIT DIRECTLY. \
This file was generated by pulling from feather repo. \
If you want to update icons to latest version, run yarn update:icons:feather **/";
const FEATHER_ICON_REPO = 'https://github.com/feathericons/feather/archive/refs/heads/master.zip';


async function main(outPath: string) {
  await prepare();

  const icons = await downloadIcons(FEATHER_ICON_REPO, /feather-master\/icons\/[0-9a-zA-Z-_]*.svg$/);
  const scaledIcons = await scaleIcons(icons, 'feather');
  const fixedIcons = await convertStrokeIconsToFill(scaledIcons);
  await writeIcons(fixedIcons, outPath, COMMENT);

  await finalize();
}

const outputPath = process.argv.slice(2)[0];
main(outputPath)
  .then(() => console.log(`All paths have been written to ${outputPath}`))
  .catch(e => console.error(JSON.stringify(e.message)))
