import {
  prepare,
  finalize,
  downloadIcons,
  scaleIcons,
  fixIcons,
  writeIcons
} from './utils';

const COMMENT = "/** DO NOT EDIT DIRECTLY. \
This file was generated by pulling from heroicons repo. \
If you want to update icons to latest version, run yarn icon:hero **/";
const HERO_ICON_REPO = 'https://github.com/tailwindlabs/heroicons/archive/refs/heads/master.zip';

async function main(outPath: string) {
  await prepare();

  const icons = await downloadIcons(HERO_ICON_REPO, /heroicons-master\/src\/outline\/[0-9a-zA-Z-_]*.svg$/);
  const scaledIcons = await scaleIcons(icons, 'hero');
  const fixedIcons = await fixIcons(scaledIcons);
  await writeIcons(fixedIcons, outPath, COMMENT);

  await finalize();
}

const outputPath = process.argv.slice(2)[0]
main(outputPath)
  .then(() => console.log(`All paths have been written to ${outputPath}`))
  .catch(e => console.error(JSON.stringify(e.message)))
